[project]
name = "scrapping-yfinance"
version = "0.1.0"
dependencies = [
    "yfinance>=0.2.40",
    "pandas>=1.3.0",
    "fastparquet",
    "boto3>=1.26.0",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"